# Generated by Django 5.2.7 on 2025-12-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BollardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupy_ratio', models.IntegerField(default=30, help_text='오토바이 차지 영역 퍼센트 (%)')),
                ('maintain_frame', models.IntegerField(default=10, help_text='볼라드 폐쇄 유지 프레임 수')),
                ('target_object', models.IntegerField(default=3, help_text='감지 대상 COCO 클래스 ID (3=오토바이)')),
                ('is_active', models.BooleanField(default=True, help_text='시스템 활성화 여부')),
                ('raspberry_pi_host', models.CharField(default='192.168.0.100', help_text='라즈베리파이 IP 주소', max_length=100)),
                ('raspberry_pi_port', models.IntegerField(default=50051, help_text='라즈베리파이 gRPC 포트 (사용 안함)')),
                ('grpc_server_port', models.IntegerField(default=50051, help_text='Django gRPC 서버 포트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '볼라드 설정',
                'verbose_name_plural': '볼라드 설정',
            },
        ),
        migrations.CreateModel(
            name='BollardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False, help_text='볼라드 닫힘 상태')),
                ('counter', models.IntegerField(default=0, help_text='유지 프레임 카운터')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manual_mode', models.BooleanField(default=False, help_text='수동 제어 모드')),
            ],
            options={
                'verbose_name': '볼라드 상태',
                'verbose_name_plural': '볼라드 상태',
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detected', models.BooleanField(help_text='객체 감지 여부')),
                ('occupy_ratio_actual', models.FloatField(blank=True, help_text='실제 측정된 점유율 (%)', null=True)),
                ('action', models.CharField(choices=[('open', '볼라드 열림'), ('close', '볼라드 닫힘'), ('none', '변화 없음')], default='none', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='감지 시점 이미지', null=True, upload_to='detection_logs/%Y/%m/%d/')),
                ('post', models.ForeignKey(blank=True, help_text='볼라드 이벤트 시 생성된 포스트', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_logs', to='blog.post')),
            ],
            options={
                'verbose_name': '감지 로그',
                'verbose_name_plural': '감지 로그',
                'ordering': ['-timestamp'],
            },
        ),
    ]
